IreniaTown_House2_MapScripts::
	.byte 0


IreniaTown_House2_NPCMan::
	lock
	faceplayer
	msgbox IreniaTown_House2_NPCMan_Text_0
	release
	end


IreniaTown_House2_NPCMan_Text_0:
	.string "Irenia Town was founded decades ago.\p"
	.string "This area was where Lugia first visited\n"
	.string "Azoria.\p"
	.string "Since that moment, we set out to create\n"
	.string "a town where everyone can join\l"
	.string "together in prayer to thank Lugia for\l"
	.string "all it's done for us.$"
